# Generated by Django 4.2.15 on 2024-09-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_production',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
